name: Go Application POD - Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'todolist/**'
  pull_request:
    branches:
      - main
    paths:
      - 'todolist/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Check Go version
      - name: Verify Go version
        run: go version


      # Step 3: Run lint
      - name: Run lint
        run: make lint

      # Step 4: Run unit tests
      - name: Run unit tests
        run: make test

      # Step 5: Start the application
      - name: Start application
        run: make up

      # Step 6: Run end-to-end tests
      - name: Run end-to-end tests
        run: make test-e2e

      # Step 7: Build Docker image
      - name: Build Docker image
        run: make docker-build

      # Step 8: Push Docker image
      - name: Push Docker image
        run: make docker-push
