name: Go Application POD - Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'todolist/**'
  pull_request:
    branches:
      - main
    paths:
      - 'todolist/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Navigate to todolist directory
      - name: Change working directory
        run: cd todolist

      # Step 3: Check Go version
      - name: Verify Go version
        run: |
          cd todolist
          go version

      # Step 4: Run lint
      - name: Run lint
        run: |
          cd todolist
          make lint

      # Step 5: Run unit tests
      - name: Run unit tests
        run: |
          cd todolist
          make test

      # Step 6: Start the application
      - name: Start application
        run: |
          cd todolist
          make up

      # Step 7: Run end-to-end tests
      - name: Run end-to-end tests
        run: |
          cd todolist
          make test-e2e

      # Step 8: Build Docker image
      - name: Build Docker image
        run: |
          cd todolist
          make docker-build

      # Step 9: Push Docker image
      - name: Push Docker image
        run: |
          cd todolist
          make docker-push
