name: Go Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'todolist/**'  # Trigger only if changes are made in /todolist
  pull_request:
    branches:
      - main
    paths:
      - 'todolist/**'  # Trigger only if changes are made in /todolist

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20

      # Step 3: Cache Go modules
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 5: Run lint
      - name: Run lint
        run: make lint

      # Step 6: Run unit tests
      - name: Run unit tests
        run: make test

      # Step 7: Start the application
      - name: Start application
        run: make up

      # Step 8: Run end-to-end tests
      - name: Run end-to-end tests
        run: make test-e2e

      # Step 9: Build Docker image
      - name: Build Docker image
        run: make docker-build

      # Step 10: Push Docker image
      - name: Push Docker image
        run: make docker-push
