name: Go Application POD - Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'todolist-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'todolist-app/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: Change working directory to todolist-app
      - name: Change working directory
        working-directory: ./todolist-app
        run: echo "Working directory set to todolist-app"

      # Step 4: Check Go version
      - name: Verify Go version
        working-directory: ./todolist-app
        run: go version

      # Step 6: Run unit tests
      - name: Run unit tests
        working-directory: ./todolist-app
        run: make test

      # Step 7: Start the application
      - name: Start application
        working-directory: ./todolist-app
        run: make up

      # Step 8: Run end-to-end tests
      - name: Run end-to-end tests
        working-directory: ./todolist-app
        run: make test-e2e

      # Step 9: Build Docker image
      - name: Build Docker image
        working-directory: ./todolist-app
        run: make docker-build

      # Step 10: Push Docker image
      - name: Push Docker image
        working-directory: ./todolist-app
        run: make docker-push
