name: Python CI with Docker and Semver

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Trigger on any changes in the entire directory
  pull_request:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 3. Install dependencies
      - name: Install dependencies
        working-directory: python-app
        run: make requirements

      # 4. Run tests
      - name: Run tests
        working-directory: python-app
        run: make test

      # 5. Lint code
      - name: Lint code
        working-directory: python-app
        run: make lint

      # 6. Build Docker image
      - name: Build Docker image
        working-directory: python-app
        run: make docker-build

      # 7. Push Docker image
      - name: Push Docker image
        working-directory: python-app
        run: make docker-push
