name: Python CI with Docker and Semver

on:
  push:
    branches:
      - main
    paths:
      - '**'  # Trigger on any changes in the entire directory
  pull_request:
    branches:
      - main
    paths:
      - '**'
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        run: make docker-login
        working-directory: python-app
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Install dependencies
      - name: Install dependencies
        working-directory: python-app
        run: make requirements

      # 5. Run tests
      - name: Run tests
        working-directory: python-app
        run: make test

      # 6. Lint code
      - name: Lint code
        working-directory: python-app
        run: make lint

      # 7. Build Docker image
      - name: Build Docker image
        working-directory: python-app
        run: make docker-build

      # 8. Push Docker image
      - name: Push Docker image
        working-directory: python-app
        run: make docker-push
